# Deep Learning with TensorFlow/Keras

This notebook demonstrates three fundamental deep learning architectures:
- **FNN (Feedforward Neural Network)** - For classification on Iris dataset
- **CNN (Convolutional Neural Network)** - For image classification on CIFAR-10
- **RNN (Recurrent Neural Network)** - For time series prediction on sine wave data

In [14]:
import tensorflow as tf
from tensorflow.keras import layers, models

## 1. Feedforward Neural Network (FNN)

**Dataset**: Iris Classification  
**Task**: Multi-class classification (3 species of iris flowers)  
**Architecture**: Dense layers with ReLU activation  
**Loss Function**: Categorical crossentropy

In [28]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

# One-hot encode labels
encoder = OneHotEncoder(sparse_output=False)  # Set sparse_output=False to get dense arrays
y = encoder.fit_transform(y)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")
print(f"y_train sample:\n{y_train[:5]}")  # Show sample of one-hot encoded labels

X_train shape: (120, 4)
y_train shape: (120, 3)
X_test shape: (30, 4)
y_test shape: (30, 3)
y_train sample:
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [29]:
# Build the FNN model
model_fnn = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(3, activation='softmax')  # 3 output classes
])

c:\Repo\Scratch\ml\mlvenv\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
# Compile and train the model
model_fnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model_fnn.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.3250 - loss: 1.6731 - val_accuracy: 0.3667 - val_loss: 1.3541
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.3250 - loss: 1.6731 - val_accuracy: 0.3667 - val_loss: 1.3541
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3250 - loss: 1.2979 - val_accuracy: 0.3667 - val_loss: 1.1207
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.3250 - loss: 1.2979 - val_accuracy: 0.3667 - val_loss: 1.1207
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3250 - loss: 1.1060 - val_accuracy: 0.3667 - val_loss: 1.0353
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3250 - loss: 1.1060 - val_accuracy: 0.3667 - val_loss: 1.0353
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2667 - loss: 1.0186 - val_accuracy: 0.3000 - val_loss: 1.0085
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2667 - loss: 1.0186 - val_accuracy: 0.3000 - val_loss: 1.0085


## 2. Convolutional Neural Network (CNN)

**Dataset**: CIFAR-10 Image Classification  
**Task**: Multi-class image classification (10 classes: airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck)  
**Architecture**: Conv2D + MaxPooling + Dense layers  
**Loss Function**: Sparse categorical crossentropy  

Implement a CNN to classify images from the CIFAR-10 dataset.

In [31]:
# Load CIFAR-10 dataset
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

In [32]:
# Build the CNN model
model_cnn = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')  # 10 output classes for CIFAR-10
])

c:\Repo\Scratch\ml\mlvenv\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [33]:
# Compile the model
model_cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model_cnn.fit(train_images, train_labels, epochs=10, batch_size=64, validation_data=(test_images, test_labels))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.4490 - loss: 1.5344 - val_accuracy: 0.5430 - val_loss: 1.3057
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.4490 - loss: 1.5344 - val_accuracy: 0.5430 - val_loss: 1.3057
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5785 - loss: 1.1917 - val_accuracy: 0.6216 - val_loss: 1.0995
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.5785 - loss: 1.1917 - val_accuracy: 0.6216 - val_loss: 1.0995
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - accuracy: 0.6350 - loss: 1.0532 - val_accuracy: 0.6539 - val_loss: 1.0054
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step - accuracy: 0.6350 - loss: 1.0532 - val_accuracy: 0.6539 - val_loss: 1.0054
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.6622 - loss: 0.9712 - val_accuracy: 0.6584 - val_loss: 0.9829
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - accuracy: 0.6622 - loss: 0.9712 - 

## 3. Recurrent Neural Network (RNN)

**Dataset**: Synthetic Sine Wave Time Series  
**Task**: Time series prediction (predict next value in sequence)  
**Architecture**: SimpleRNN + Dense layer  
**Loss Function**: Mean Squared Error (MSE)  

Generate synthetic sine wave data and use RNN to predict future values.

In [19]:
import numpy as np

# Generate synthetic sine wave data
t = np.linspace(0, 100, 10000)
X = np.sin(t).reshape(-1, 1)

# Prepare sequences
def create_sequences(data, seq_length):
    X_seq, y_seq = [], []
    for i in range(len(data) - seq_length):
        X_seq.append(data[i:i+seq_length])
        y_seq.append(data[i+seq_length])
    return np.array(X_seq), np.array(y_seq)

seq_length = 100
X_seq, y_seq = create_sequences(X, seq_length)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42)

In [20]:
# Build the RNN model
model_rnn = models.Sequential([
    layers.SimpleRNN(128, input_shape=(seq_length, 1)),
    layers.Dense(1)  # Output is a single value (next point in the sequence)
])

c:\Repo\Scratch\ml\mlvenv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [21]:
# Compile the model
model_rnn.compile(optimizer='adam', loss='mse')

# Train the model
model_rnn.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 0.0026 - val_loss: 3.9381e-06
Epoch 2/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 4.2533e-06 - val_loss: 1.6868e-05
Epoch 3/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 5.9481e-06 - val_loss: 1.1358e-06
Epoch 4/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 1.2886e-05 - val_loss: 2.0975e-06
Epoch 5/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - loss: 1.3098e-06 - val_loss: 1.1636e-06
Epoch 6/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 2.3059e-06 - val_loss: 6.3678e-06
Epoch 7/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 1.5480e-05 - val_loss: 4.2491e-05
Epoch 8/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 3.4878e-05 - val_loss: 4.7714e-05
Epoch 9/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - loss: 9.2259e-06 - val_loss: 1.9550e-06
Epoch 10/10
248/248 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 8.1011e-07 - val_loss: 1.3516e-06
